use anyhow::{Context, Result};
use chrono::Local;
use std::fs;
use std::io::Write;
use std::path::PathBuf;
use std::process::{Command, Stdio};

use crate::config;

/// (post_url, dead_url, archive_url)
pub type DeadItem = (String, String, String);

pub fn macos_notification(title: &str, message: &str) -> Result<()> {
    let script = r#"on run
    set theTitle to (system attribute "AS_TITLE")
    set theMsg to (system attribute "AS_MSG")
    display notification theMsg with title theTitle sound name "Glass"
end run"#;
    run_osascript(script, &[("AS_TITLE", title), ("AS_MSG", message)])
}

pub fn apple_mail(to: &str, subject: &str, body: &str) -> Result<()> {
    let script = r#"on run
    set theSubject to (system attribute "AS_SUBJECT")
    set theBody to (system attribute "AS_BODY")
    set theTo to (system attribute "AS_TO")
    tell application "Mail"
        set newMessage to make new outgoing message with properties {subject:theSubject, content:theBody, visible:false}
        tell newMessage
            make new to recipient at end of to recipients with properties {address:theTo}
        end tell
        send newMessage
    end tell
end run"#;
    run_osascript(
        script,
        &[("AS_TO", to), ("AS_SUBJECT", subject), ("AS_BODY", body)],
    )
}

fn run_osascript(script: &str, env: &[(&str, &str)]) -> Result<()> {
    let mut cmd = Command::new("osascript")
        .stdin(Stdio::piped())
        .stdout(Stdio::null())
        .stderr(Stdio::piped())
        .envs(env.iter().copied())
        .spawn()
        .context("spawn osascript (requires macOS)")?;
    if let Some(mut stdin) = cmd.stdin.take() {
        stdin.write_all(script.as_bytes())?;
    }
    let out = cmd.wait_with_output()?;
    if !out.status.success() {
        let stderr = String::from_utf8_lossy(&out.stderr);
        anyhow::bail!("osascript failed: {}", stderr.trim());
    }
    Ok(())
}

/// Appends a dated section to SUBSTACK_DEAD_LINKS.md at the repo root.
/// Returns the path written if anything was appended.
pub fn append_substack_todo(items: &[DeadItem]) -> Result<Option<PathBuf>> {
    if items.is_empty() {
        return Ok(None);
    }
    let path = config::repo_root().join("SUBSTACK_DEAD_LINKS.md");
    let mut content = if path.exists() {
        fs::read_to_string(&path).unwrap_or_default()
    } else {
        String::from(
            "# Substack dead links\n\n\
             Generated by `archiver maintain`. Local archives are already published on \
             croissanthology.com — these are the substack posts that still need manual \
             link patches. Tick the box once you've updated the substack post.\n\n",
        )
    };
    if !content.ends_with('\n') {
        content.push('\n');
    }
    content.push_str(&format!(
        "## {}\n\n",
        Local::now().format("%Y-%m-%d")
    ));
    for (post, dead, archive) in items {
        content.push_str(&format!(
            "- [ ] **{}**\n  - dead: `{}`\n  - archive: <{}>\n\n",
            post, dead, archive
        ));
    }
    fs::write(&path, content)?;
    Ok(Some(path))
}

pub fn render_mail_body(items: &[DeadItem]) -> String {
    let mut body = String::from(
        "hi margot — these substack posts cite links that have gone dead.\n\
         local archives are already live on croissanthology.com.\n\
         update substack manually when you get a sec.\n\n",
    );
    for (post, dead, archive) in items {
        body.push_str(&format!(
            "post:    {}\ndead:    {}\narchive: {}\n\n",
            post, dead, archive
        ));
    }
    body.push_str("— archiver 🐾\n");
    body
}

pub fn terminal_bell() {
    print!("\x07");
}
